[build]
  environment = { NODE_VERSION = "12.0.0" }
  #command = "npm run build"
  publish = "dist"
[template.environment]
  KEYSTONE_API = "Paste your Keystone API URL here"
[[redirects]]
  from = "/posts-gated/*"
  to = "/posts-gated/:splat"
  status = 200
  force = true
  conditions = {Role = ["subscriber"]}
[[redirects]]
  from = "/posts-gated/*"
  to = "/login"
  status = 401
  force = true
